# Site settings
title: HCURA
header-img: images/galaxy-bg.jpg
email: board@hcura.org
description: "Site for Harvard College Undergraduate Research Association (HCURA)"
baseurl: ""
url: "http://hcura.org"
github_username:  kraftp/hcura_website
facebook_username:  harvardresearch

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["README.md", node_modules/, js/]
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
